name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Создаем папку в домашней директории пользователя (это безопаснее всего)
            mkdir -p ~/app-deploy
            cd ~/app-deploy
            
            # Чистая синхронизация с GitHub
            git init
            git remote add origin git@github.com:dresky2024/my-devops-test.git || git remote set-url origin git@github.com:dresky2024/my-devops-test.git
            git fetch origin main
            git reset --hard origin/main
            
            # Запуск через Docker Compose
            sudo docker-compose up -d --build


