name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим по абсолютному пути, который мы увидели в логах
            cd /root/my-devops-test
            
            # Принудительно чиним Git, если он "сломался"
            git init
            git remote add origin git@github.com:dresky2024/my-devops-test.git || git remote set-url origin git@github.com:dresky2024/my-devops-test.git
            
            # Забираем код и сбрасываем состояние до идеального
            git fetch origin
            git reset --hard origin/main
            
            # Запускаем сборку
            sudo docker-compose up -d --build


